# Generated by Django 4.2.5 on 2026-05-21 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('titre_court', models.CharField(max_length=100, verbose_name='Titre court')),
                ('description_courte', models.TextField(verbose_name='Description courte')),
                ('description_longue', models.TextField(verbose_name='Description détaillée')),
                ('icon', models.CharField(default='fas fa-leaf', max_length=100, verbose_name='Icône Font Awesome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activites/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts (un par ligne)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('information', "Demande d'information"), ('collaboration', 'Proposition de collaboration'), ('projet', 'Soumission de projet'), ('stage', 'Demande de stage'), ('autre', 'Autre')], default='information', max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/', verbose_name='Photo')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste/Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('specialite', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='FamilleBotanique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la famille')),
                ('nom_latin', models.CharField(blank=True, max_length=200, verbose_name='Nom latin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('caracteristiques', models.TextField(blank=True, verbose_name='Caractéristiques')),
                ('image', models.ImageField(blank=True, null=True, upload_to='familles/', verbose_name='Image représentative')),
                ('ordre', models.CharField(blank=True, max_length=200, verbose_name='Ordre botanique')),
                ('nombre_especes', models.IntegerField(default=0, verbose_name="Nombre d'espèces")),
            ],
            options={
                'verbose_name': 'Famille botanique',
                'verbose_name_plural': 'Familles botaniques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordre', 'question'],
            },
        ),
        migrations.CreateModel(
            name='GenreBotanique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du genre')),
                ('nom_latin', models.CharField(blank=True, max_length=200, verbose_name='Nom latin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nombre_especes', models.IntegerField(default=0, verbose_name="Nombre d'espèces")),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='api.famillebotanique', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Genre botanique',
                'verbose_name_plural': 'Genres botaniques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HerbierStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plantes', models.IntegerField(default=0)),
                ('total_familles', models.IntegerField(default=0)),
                ('total_genres', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('dernier_ajout', models.DateTimeField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Statistique Herbier',
                'verbose_name_plural': 'Statistiques Herbier',
            },
        ),
        migrations.CreateModel(
            name='Methodologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='fas fa-clipboard-list', max_length=100, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Étape de méthodologie',
                'verbose_name_plural': 'Étapes de méthodologie',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type de partenaire')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('categorie', models.CharField(choices=[('recherche', 'Recherche'), ('conservation', 'Conservation'), ('formation', 'Formation'), ('developpement', 'Développement')], default='recherche', max_length=50, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('termine', 'Terminé'), ('encours', 'En cours'), ('planifie', 'Planifié')], default='encours', max_length=50, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet à la une')),
                ('annee', models.CharField(max_length=50, verbose_name='Année ou période')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('partenaires', models.IntegerField(default=0, verbose_name='Nombre de partenaires')),
                ('beneficiaires', models.CharField(blank=True, max_length=100, verbose_name='Bénéficiaires')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('impact', models.CharField(blank=True, max_length=200, verbose_name='Impact')),
                ('progression', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image principale')),
                ('images_galerie', models.JSONField(blank=True, default=list, verbose_name='Images de la galerie')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, verbose_name='Objectifs')),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-featured', '-annee'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('auteurs', models.CharField(max_length=500, verbose_name='Auteurs')),
                ('journal', models.CharField(max_length=200, verbose_name='Journal/Revue')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Image')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-annee', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('texte_botanique', models.TextField(verbose_name='Texte botanique')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Image')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image externe")),
                ('lien', models.URLField(blank=True, verbose_name='Lien associé')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur')),
                ('unite', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unité')),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=100, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste')),
                ('organisation', models.CharField(max_length=200, verbose_name='Organisation')),
                ('texte', models.TextField(verbose_name='Témoignage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/', verbose_name='Photo')),
                ('note', models.IntegerField(default=5, verbose_name='Note (/5)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProjetTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='api.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Étape du projet',
                'verbose_name_plural': 'Étapes des projets',
                'ordering': ['projet', 'annee', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la plante')),
                ('nom_scientifique', models.CharField(blank=True, max_length=200, verbose_name='Nom scientifique')),
                ('description', models.TextField(verbose_name='Description')),
                ('habitat', models.TextField(blank=True, verbose_name='Habitat')),
                ('distribution', models.CharField(blank=True, max_length=500, verbose_name='Distribution')),
                ('statut_conservation', models.CharField(blank=True, max_length=100, verbose_name='Statut de conservation')),
                ('usages', models.TextField(blank=True, verbose_name='Usages traditionnels')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plantes/', verbose_name='Image principale')),
                ('images_galerie', models.JSONField(blank=True, default=list, verbose_name="Galerie d'images")),
                ('featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantes', to='api.famillebotanique', verbose_name='Famille')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantes', to='api.genrebotanique', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Plante',
                'verbose_name_plural': 'Plantes',
                'ordering': ['nom'],
            },
        ),
    ]
