# Generated by Django 5.2.17 on 2026-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plante',
            options={'ordering': ['nom_scientifique'], 'verbose_name': 'Plante', 'verbose_name_plural': 'Plantes'},
        ),
        migrations.RemoveField(
            model_name='plante',
            name='nom',
        ),
        migrations.AddField(
            model_name='plante',
            name='affinite_chorologique',
            field=models.CharField(blank=True, default='', help_text='Ex : Soudano-zambézienne, guinéenne…', max_length=200, verbose_name='Affinité chorologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='affinite_ecologique',
            field=models.CharField(blank=True, default='', help_text='Ex : Mésophile, xérophile, hygrophile…', max_length=200, verbose_name='Affinité écologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='lieu_collecte',
            field=models.CharField(blank=True, default='', help_text='Ex : Mont Tonkoui, Man', max_length=300, verbose_name='Lieu de collecte'),
        ),
        migrations.AddField(
            model_name='plante',
            name='nom_vernaculaire',
            field=models.CharField(blank=True, default='', help_text='Nom commun en langue locale', max_length=200, verbose_name='Nom vernaculaire'),
        ),
        migrations.AddField(
            model_name='plante',
            name='type_biologique',
            field=models.CharField(blank=True, default='', help_text='Ex : Phanérophyte, thérophyte, hémicryptophyte…', max_length=200, verbose_name='Type biologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='type_morphologique',
            field=models.CharField(blank=True, default='', help_text='Ex : Arbre, arbuste, herbe, liane…', max_length=200, verbose_name='Type morphologique'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='distribution',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Distribution géographique'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='habitat',
            field=models.TextField(blank=True, default='', verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, help_text="Liste de chemins d'images supplémentaires", verbose_name="Galerie d'images (liste de chemins)"),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom_scientifique',
            field=models.CharField(help_text='Ex : Khaya senegalensis', max_length=200, verbose_name='Nom scientifique'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='statut_conservation',
            field=models.CharField(choices=[('CR', 'En danger critique'), ('EN', 'En danger'), ('VU', 'Vulnérable'), ('NT', 'Quasi menacé'), ('LC', 'Préoccupation mineure'), ('NE', 'Non évaluée')], default='NE', max_length=2, verbose_name='Statut de conservation (UICN)'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='usages',
            field=models.TextField(blank=True, default='', verbose_name='Usages traditionnels'),
        ),
        migrations.AddIndex(
            model_name='plante',
            index=models.Index(fields=['nom_scientifique'], name='api_plante_nom_sci_0091c7_idx'),
        ),
        migrations.AddIndex(
            model_name='plante',
            index=models.Index(fields=['statut_conservation'], name='api_plante_statut__1c2227_idx'),
        ),
    ]
