# Generated by Django 5.2.17 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plante_options_remove_plante_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images (chemins)"),
        ),
        migrations.AddField(
            model_name='herbierstats',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images (chemins)"),
        ),
        migrations.AddField(
            model_name='publication',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images (chemins)"),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images (chemins)"),
        ),
    ]
