# Generated by Django 5.2.17 on 2026-09-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activite_images_galerie_herbierstats_images_galerie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='partenaires',
            new_name='partenaires_count',
        ),
    ]
