services:
  - type: web
    name: herbier-admin-backend
    runtime: python
    rootDir: admin-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin_auth.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.10
