# Generated by Django 6.0.5 on 2026-05-10 10:56

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, unique=True, validators=[api.models.validate_phone_number], verbose_name='Numéro de téléphone')),
                ('pays', models.CharField(blank=True, default='CI', max_length=10, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=False, verbose_name='Compte actif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Super Administrateur',
                'verbose_name_plural': 'Super Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='HerbierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantes', models.JSONField(default=list, verbose_name='Plantes')),
                ('equipe', models.JSONField(default=list, verbose_name='Équipe')),
                ('partenaires', models.JSONField(default=list, verbose_name='Partenaires')),
                ('slides', models.JSONField(default=list, verbose_name='Slides')),
                ('projets', models.JSONField(default=list, verbose_name='Projets')),
                ('activites', models.JSONField(default=list, verbose_name='Activités')),
                ('temoignages', models.JSONField(default=list, verbose_name='Témoignages')),
                ('publications', models.JSONField(default=list, verbose_name='Publications')),
                ('faqs', models.JSONField(default=list, verbose_name='FAQs')),
                ('statistiques', models.JSONField(default=list, verbose_name='Statistiques')),
                ('methodologie', models.JSONField(default=list, verbose_name='Méthodologie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donnée Herbier',
                'verbose_name_plural': 'Données Herbier',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
            },
        ),
    ]
