# Generated by Django 4.2.7 on 2026-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activites/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipe/'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires/'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plantes/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/'),
        ),
    ]
