# Generated by Django 4.2.7 on 2026-07-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activite_image_alter_equipe_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='requires_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
