# Generated by Django 4.2.7 on 2026-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_otpcode_type_alter_superadmin_role_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='role',
            field=models.CharField(choices=[('it_admin', 'IT Administrator'), ('admin', 'Administrateur'), ('viewer', 'Visualisateur')], default='admin', max_length=20),
        ),
    ]
