# Generated by Django 4.2.7 on 2026-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_otpcode_type_alter_superadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='totp_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='totp_last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
