# Generated by Django 4.2.7 on 2026-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_superadmin_totp_backup_codes_superadmin_totp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='api_loginat_email_420782_idx'), models.Index(fields=['ip_address', '-created_at'], name='api_loginat_ip_addr_49b2c4_idx')],
            },
        ),
    ]
