# Generated by Django 4.2.7 on 2026-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification_userknownip'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
