# Generated by Django 4.2.7 on 2026-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_publication_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activite',
            name='points_forts',
            field=models.TextField(blank=True, default='', help_text='Un point fort par ligne'),
        ),
    ]
