# Generated by Django 4.2.7 on 2026-09-19 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activite_caption_activite_points_forts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plante',
            options={'ordering': ['nom_scientifique'], 'verbose_name': 'Plante', 'verbose_name_plural': 'Plantes'},
        ),
        migrations.RemoveField(
            model_name='plante',
            name='nom',
        ),
        migrations.AddField(
            model_name='plante',
            name='affinite_chorologique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Affinité chorologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='affinite_ecologique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Affinité écologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images"),
        ),
        migrations.AddField(
            model_name='plante',
            name='lieu_collecte',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Lieu de collecte'),
        ),
        migrations.AddField(
            model_name='plante',
            name='nom_vernaculaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom vernaculaire'),
        ),
        migrations.AddField(
            model_name='plante',
            name='type_biologique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type biologique'),
        ),
        migrations.AddField(
            model_name='plante',
            name='type_morphologique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type morphologique'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='plante',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='famille',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Famille'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='habitat',
            field=models.TextField(blank=True, null=True, verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plantes/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='plante',
            name='nom_scientifique',
            field=models.CharField(default='hello', max_length=200, verbose_name='Nom scientifique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plante',
            name='statut_conservation',
            field=models.CharField(choices=[('CR', 'En danger critique'), ('EN', 'En danger'), ('VU', 'Vulnérable'), ('NT', 'Quasi menacé'), ('LC', 'Préoccupation mineure'), ('NE', 'Non évaluée')], default='NE', max_length=2, verbose_name='Statut de conservation (UICN)'),
        ),
    ]
