# Generated by Django 4.2.7 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_plante_options_remove_plante_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, verbose_name="Galerie d'images (chemins)"),
        ),
    ]
