# Generated by Django 4.2.7 on 2026-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_activite_images_galerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='description_longue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='images_galerie',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="Galerie d'images (chemins)"),
        ),
        migrations.AddField(
            model_name='projet',
            name='partenaires_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.IntegerField(default=0),
        ),
    ]
