# Generated by Django 4.2.7 on 2026-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Projet à la une'),
        ),
    ]
